### ISSUE TITLE
Parser parses LTLPrefixOperatorNode as LTLBPredicateNode

### ISSUE THREAD

**Issue by Mareikes** [hhu-stups/bmoth#99] opened 2017-06-23 11:49 UTC
example in not( {...} U {...}) , possibly for other cases as well (weak_until)

in LTLTransformationTest.java

**Comment by dohan** [comment] 2017-06-28 15:06
There is no ignored unit test in LTLTransformationTest.java. Is the issue out-dated? Otherwise, can you provide a unit test.

**Comment by wysiib** [comment] 2017-06-30 10:46
duplicate of #100

**Closed as completed by wysiib** 2017-06-30 10:46 UTC
Labels: duplicate
