### ISSUE TITLE
Preferences create Warning on Windows

### ISSUE THREAD

**Issue by Lunnaris01** [hhu-stups/bmoth#63] opened 2017-05-12 16:03 UTC
Mai 12, 2017 5:54:44 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

When starting the App.

**Comment by wysiib** [comment] 2017-05-15 12:48
Apparently, the issue is caused by the JDK / JRE. See [Stackoverflow](http://stackoverflow.com/questions/18559000/reading-and-writing-from-to-java-preferences-fails-on-fresh-windows-8).

I just checked on Windows and preferences work as intended despite the warning. Thus, I'm closing the issue as wontfix as it has to be fixed upstream.

**Closed by wysiib** 2017-05-15 12:48 UTC
Labels: bug, wontfix
